# Generated by Django 3.1.5 on 2021-01-13 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0040_auto_20210113_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
