# Generated by Django 3.1.5 on 2021-01-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0041_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
