# Generated by Django 3.1.5 on 2021-01-13 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Axis', '0042_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
